app/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from cleaning import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(urls)),
]

cleaning/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from . import views

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', LogoutView.as_view(next_page='order_lists'), name='logout'),
    path('',views.index, name='order_lists'),
    path('create_order/', views.create_order, name="create_order"),
]

cleaning/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin

class UserManager(BaseUserManager):
    def create_user(self, login, email, password=None, **extra_fields):
        if not email:
            raise ValueError('Email is required')
        email = self.normalize_email(email)
        user = self.model(login=login, email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, login, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self.create_user(login, email, password, **extra_fields)

class Users(AbstractBaseUser, PermissionsMixin):
    full_name = models.CharField(max_length=100)
    phone = models.CharField(max_length=12)
    email = models.EmailField(unique=True)
    login = models.CharField(max_length=50, unique=True)
    password = models.CharField(max_length=200)

    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'login'
    REQUIRED_FIELDS = ['email', 'full_name']

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"

    def __str__(self):
        return self.full_name

class Services(models.Model):
    name = models.CharField(
        verbose_name="Название услуги",
        blank=False,
        max_length = 100,
    )

    service_type = models.CharField(
        verbose_name = "Тип услуги",
        blank=False,
        max_length = 100,
    )

    price = models.IntegerField(
        verbose_name = "Цена в рублях",
        blank=False,
    )

    class Meta:
        verbose_name = "Услугa"
        verbose_name_plural = "Услуги"
    
    def __str__(self):
        return self.name
    
class Order(models.Model):
    STATUS_CHOICES = [ 
        ('new', 'Новая заявка'),
        ('completed', 'Услуга оказана'),
        ('cancelled', 'Услуга отменена')
    ]

    TYPE_OF_PAYMENT = {
        ('cash', 'Наличными'),
        ('cards', 'Картой'),
    }

    address = models.CharField(
        verbose_name = "Адрес",
        blank = False,
        max_length = 100,
    )

    contact_data = models.CharField(
        verbose_name = "Контактная информация",
        blank = False,
        max_length = 12,
    )

    service_id = models.ForeignKey(
        Services,
        on_delete=models.CASCADE,
        blank = False,
        verbose_name="Услуги"
    )

    user_id = models.ForeignKey(
        Users,
        on_delete=models.CASCADE,
        blank = False,
    )

    payment_type = models.CharField(
        verbose_name = "Тип оплаты",
        blank = False,
        choices=TYPE_OF_PAYMENT,
        default='cash',
        max_length = 40,
    )

    status = models.CharField(
        verbose_name="Статус заявки",
        max_length=10,
        choices=STATUS_CHOICES,
        default='new',
        blank=False,
    )

    date_time = models.DateTimeField(
        verbose_name="Дата и время",
        blank=False
    )

    class Meta:
        verbose_name = "Заявка"
        verbose_name_plural = "Заявки"
    
    def __str__(self):
        return self.contact_data
    

cleaning/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import Users, Order
from django.contrib.auth import authenticate

class UserRegistrationForm(UserCreationForm):
    login = forms.CharField(label='Имя пользователя')
    email = forms.CharField(label='Эллектронная почта')
    full_name = forms.CharField(label='ФИО')
    phone = forms.CharField(label='Номер телефона')
    
    class Meta:
        model = Users
        fields = ['login', 'email', 'full_name', 'password1', 'password2', 'phone']

class UserLoginForm(forms.ModelForm):
    login = forms.CharField(label='Имя пользователя')
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput)

    class Meta:
        model = Users
        fields = ['login', 'password']

    def clean(self):
        login = self.cleaned_data.get('login')
        password = self.cleaned_data.get('password')
        if login and password:
            user = authenticate(login=login, password=password)
            if not user:
                raise forms.ValidationError('Неправильный логин или пароль.')
        return self.cleaned_data

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['address', 'contact_data', 'service_id', 'payment_type', 'date_time']
        widgets = {
            'date_time': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
        }

cleaning/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from .forms import UserRegistrationForm, UserLoginForm, OrderForm
from django.contrib.auth.models import AnonymousUser
from .models import *

def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            login(request, form.instance)
            return redirect('order_lists')
    else:
        form = UserRegistrationForm()
    return render(request, 'auth/register.html', {'form': form})

def user_login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            user = authenticate(login=form.cleaned_data['login'], password=form.cleaned_data['password'])
            print(user)
            if user is not None:
                login(request, user)
                return redirect('order_lists')
            else:
                form.add_error(None, 'Введите правильный логин и пароль. Оба поля могут быть чувствительны к регистру.')
    else:
        form = UserLoginForm()
    return render(request, 'auth/login.html', {'form': form})

def index(request):
    if isinstance(request.user, AnonymousUser):
        data = {
            'orders': 'Здесь пока пустота'
        }
    else:
        user_orders = Order.objects.filter(user_id=request.user)
        data = {
            'orders': user_orders,
        }
    return render(request, "index.html", data)


def create_order(request):
    data = {
        "order_form": OrderForm(),
    }

    if request.method == 'POST':
        order_form = OrderForm(request.POST)
        if order_form.is_valid():
            order = order_form.save(commit=False)
            order.user_id = request.user
            order.save()
            return redirect('order_lists')

    return render(request, 'create_order.html', data)

cleaning/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block styles %}
    {% endblock %}
    <link rel="stylesheet" href="{% static 'main.css' %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <header>
        <div class="burger" onclick="toggleMenu()">
            <div></div>
            <div></div>
            <div></div>
        </div>
        <nav>
            <a href="/">История Заявок</a>
            {% if user.is_authenticated %}
                <a href="/create_order/">Создать Заявку</a>
                {% if user.is_superuser %}
                    <a href="/admin/">Админ-панель</a>
                {% endif %}
                <a href="#" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">Выход</a>
                <form id="logout-form" action="{% url 'logout' %}" method="post" style="display: none;">
                    {% csrf_token %}
                </form>
            {% else %}
                <a href="{% url 'login' %}">Вход</a>
                <a href="{% url 'register' %}">Регистрация</a>
            {% endif %}
        </nav>
    </header>    
    <main>
        {% block content %}
        {% endblock %}
    </main>
    {% block scripts %}
    {% endblock %}
    <script>
        function toggleMenu() {
            const nav = document.querySelector('header > nav');
            nav.classList.toggle('active');
        }
    </script>
</body>
</html>

cleaning/templates/create_order.html
{% extends "base.html" %}
{% load static %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'form.css' %}">
{% endblock styles %}

{% block content %}
<div class="create-order-form-container">
    <form method="post" class="create-order-form">
        <h2>Создать заказ</h2>
        {% csrf_token %}
        {% for field in order_form %}
            <div class="form-group">
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {{ field }}
                {% if field.errors %}
                    <div class="error">{{ field.errors }}</div>
                {% endif %}
            </div>
        {% endfor %}
        <button type="submit">Создать заказ</button>
    </form>
</div>
{% endblock content %}

cleaning/templates/index.html
{% extends "base.html" %}
{% load static %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'index.css' %}">
{% endblock styles %}

{% block content %}
<article class="orders-history">
    <h2>История заявок</h2>
    {% if orders == 'Здесь пока пустота' %}
        <p class="else">{{orders}}</p>
    {% else %}
    <div>
        {%for order in orders%}
            <article>
                <h2>Вид услуги: {{ order.service_id }}</h2>
                <p><span>Адрес:</span> {{ order.address }}</p>
                <p><span>Тип оплаты:</span> {{ order.get_payment_type_display }}</p>
                <p><span>Статус:</span> {{ order.get_status_display }}</p>
                <p><span>Дата и время:</span> {{ order.date_time }}</p>
                <p><span>Котактная информация:</span> {{ order.contact_data }}</p>
            </article>
        {% endfor %}
    </div>
    {% endif %}
</article>
{% endblock content %}